/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewBeanForm.java
 *
 * Created on 5.4.2012, 10:57:27
 */
package samoojacitvenoucenje.GUI;


import java.awt.GridLayout;
import java.awt.Label;
/**
 *
 * @author Evgen
 */
public class NewBeanForm extends GridLayout {

    /** Creates new form NewBeanForm */
    public NewBeanForm() {
    
        this.setRows(5);
        this.setColumns(5);
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }
    // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
